# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'currenciesPrototype' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   
    pod 'FirebaseCore', '~> 5.4'
    pod 'FirebaseMLVision', '~> 0.15'
    pod 'Fabric', '~> 1.9'
    pod 'Crashlytics', '~> 3.12'
    pod 'Alamofire', '~> 4.7'
    pod 'ReachabilitySwift', '~> 4.3'
    pod 'Zip', '~> 1.1'
    pod 'GoogleTagManager', '~> 7.1'
    pod 'Swinject', '~> 2.6'
    pod 'SwinjectStoryboard', '~> 2.2'
    pod 'lottie-ios', '~> 3.0'



end
